import Header from "@/components/header/Header/Header";
import { inter, calistoga } from "@/utils/fonts/fonts";

import "../scss/main.scss";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter} ${calistoga}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
